import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Pooja Items (8 products)
        {
            name: 'Camphor (Kapur)',
            category: 'Pooja Items',
            mrp: 50,
            sellingPrice: 45,
            unit: 'packet',
            barcode: 'BAR001',
            stockQuantity: 50,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Agarbatti (Incense Sticks)',
            category: 'Pooja Items',
            mrp: 30,
            sellingPrice: 25,
            unit: 'packet',
            barcode: 'BAR002',
            stockQuantity: 100,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Dhoop Sticks',
            category: 'Pooja Items',
            mrp: 40,
            sellingPrice: 35,
            unit: 'box',
            barcode: 'BAR003',
            stockQuantity: 40,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Kumkum (Sindoor)',
            category: 'Pooja Items',
            mrp: 20,
            sellingPrice: 18,
            unit: 'packet',
            stockQuantity: 60,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Haldi Powder (Turmeric)',
            category: 'Pooja Items',
            mrp: 60,
            sellingPrice: 55,
            unit: 'packet',
            barcode: 'BAR004',
            stockQuantity: 35,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Diya (Clay Lamp)',
            category: 'Pooja Items',
            mrp: 10,
            sellingPrice: 8,
            unit: 'piece',
            stockQuantity: 200,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Pooja Oil',
            category: 'Pooja Items',
            mrp: 80,
            sellingPrice: 75,
            unit: 'liter',
            barcode: 'BAR005',
            stockQuantity: 25,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Coconut',
            category: 'Pooja Items',
            mrp: 35,
            sellingPrice: 30,
            unit: 'piece',
            stockQuantity: 50,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Groceries (8 products)
        {
            name: 'Basmati Rice',
            category: 'Groceries',
            mrp: 120,
            sellingPrice: 110,
            unit: 'kg',
            barcode: 'BAR006',
            stockQuantity: 100,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Toor Dal',
            category: 'Groceries',
            mrp: 140,
            sellingPrice: 130,
            unit: 'kg',
            barcode: 'BAR007',
            stockQuantity: 80,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Mustard Oil',
            category: 'Groceries',
            mrp: 180,
            sellingPrice: 170,
            unit: 'liter',
            barcode: 'BAR008',
            stockQuantity: 40,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Wheat Flour (Atta)',
            category: 'Groceries',
            mrp: 50,
            sellingPrice: 45,
            unit: 'kg',
            barcode: 'BAR009',
            stockQuantity: 150,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Sugar',
            category: 'Groceries',
            mrp: 45,
            sellingPrice: 42,
            unit: 'kg',
            barcode: 'BAR010',
            stockQuantity: 100,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Tea Powder',
            category: 'Groceries',
            mrp: 200,
            sellingPrice: 190,
            unit: 'packet',
            barcode: 'BAR011',
            stockQuantity: 50,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Salt',
            category: 'Groceries',
            mrp: 20,
            sellingPrice: 18,
            unit: 'kg',
            stockQuantity: 100,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Red Chilli Powder',
            category: 'Groceries',
            mrp: 80,
            sellingPrice: 75,
            unit: 'packet',
            barcode: 'BAR012',
            stockQuantity: 45,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Stationary (7 products)
        {
            name: 'Notebook (Single Line)',
            category: 'Stationary',
            mrp: 40,
            sellingPrice: 35,
            unit: 'piece',
            barcode: 'BAR013',
            stockQuantity: 120,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Pen (Blue)',
            category: 'Stationary',
            mrp: 10,
            sellingPrice: 8,
            unit: 'piece',
            barcode: 'BAR014',
            stockQuantity: 300,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Pencil',
            category: 'Stationary',
            mrp: 5,
            sellingPrice: 4,
            unit: 'piece',
            stockQuantity: 250,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Eraser',
            category: 'Stationary',
            mrp: 5,
            sellingPrice: 4,
            unit: 'piece',
            stockQuantity: 200,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Sharpener',
            category: 'Stationary',
            mrp: 5,
            sellingPrice: 4,
            unit: 'piece',
            stockQuantity: 150,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Scale (15cm)',
            category: 'Stationary',
            mrp: 10,
            sellingPrice: 8,
            unit: 'piece',
            barcode: 'BAR015',
            stockQuantity: 100,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Geometry Box',
            category: 'Stationary',
            mrp: 80,
            sellingPrice: 70,
            unit: 'box',
            barcode: 'BAR016',
            stockQuantity: 40,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Personal Care (7 products)
        {
            name: 'Lux Soap',
            category: 'Personal Care',
            mrp: 35,
            sellingPrice: 30,
            unit: 'piece',
            barcode: 'BAR017',
            stockQuantity: 80,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Colgate Toothpaste',
            category: 'Personal Care',
            mrp: 50,
            sellingPrice: 45,
            unit: 'piece',
            barcode: 'BAR018',
            stockQuantity: 60,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Shampoo Sachet',
            category: 'Personal Care',
            mrp: 10,
            sellingPrice: 8,
            unit: 'piece',
            stockQuantity: 150,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Hair Oil',
            category: 'Personal Care',
            mrp: 120,
            sellingPrice: 110,
            unit: 'packet',
            barcode: 'BAR019',
            stockQuantity: 50,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Face Wash',
            category: 'Personal Care',
            mrp: 150,
            sellingPrice: 140,
            unit: 'piece',
            barcode: 'BAR020',
            stockQuantity: 30,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Talcum Powder',
            category: 'Personal Care',
            mrp: 100,
            sellingPrice: 90,
            unit: 'packet',
            barcode: 'BAR021',
            stockQuantity: 40,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Body Lotion',
            category: 'Personal Care',
            mrp: 180,
            sellingPrice: 165,
            unit: 'piece',
            barcode: 'BAR022',
            stockQuantity: 25,
            isActive: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully - 30 products added');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});